export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_MIN_MAX_PRODUCTS = 'SET_MIN_MAX_PRODUCTS';
export const SET_INPUT_RANGE_VALUE = 'SET_INPUT_RANGE_VALUE';
export const SET_PRODUCTS_TOTAL = 'SET_PRODUCTS_TOTAL';

export const SET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const PRICE_RANGE_REQUESTED_HANDLER = 'PRICE_RANGE_REQUESTED_HANDLER';
export const UPDATE_SORT_BY = 'UPDATE_SORT_BY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const PAGINATION_HANDLER = 'PAGINATION_HANDLER';
export const RESET_CATEGORY = 'RESET_CATEGORY';
