export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_MIN_MAX_PRODUCTS = 'SET_MIN_MAX_PRODUCTS';
export const SET_INPUT_RANGE_VALUE = 'SET_INPUT_RANGE_VALUE';
export const SET_PRODUCTS_TOTAL = 'SET_PRODUCTS_TOTAL';
export const SET_INITIAL_PRODUCTS_PRICE = 'SET_INITIAL_PRODUCTS_PRICE';
export const SET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const PRICE_RANGE_REQUESTED_HANDLER = 'PRICE_RANGE_REQUESTED_HANDLER';
export const UPDATE_SORT_BY = 'UPDATE_SORT_BY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const PAGINATION_HANDLER = 'PAGINATION_HANDLER';


export const RESET_CATEGORY = 'RESET_CATEGORY';
export const RESET_CURRENT_PAGE = 'RESET_CURRENT_PAGE';


export const SET_LOADING_TO_TRUE = 'SET_LOADING_TO_TRUE';
export const SET_LOADING_TO_FALSE = 'SET_LOADING_TO_FALSE';


export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FALIED';
export const SET_LOGIN_STATE_TO_TRUE = 'SET_LOGIN_STATE_TO_TRUE';
export const SET_LOGIN_STATE_TO_FALSE = 'SET_LOGIN_STATE_TO_FALSE';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const SET_PRODUCTS_TO_CART = 'SET_PRODUCTS_TO_CART';
export const CLEAR_PRODUCTS_IN_CART = 'CLEAR_PRODUCTS_IN_CART';

export const ADD_USER_INFO = 'ADD_USER_INFO'