export const SET_PRODUCTS = 'SET_PRODUCTS';
export const SET_MIN_MAX_PRODUCTS = 'SET_MIN_MAX_PRODUCTS';
export const INPUT_RANGE_CHANGE_HANDLER = 'INPUT_RANGE_CHANGE_HANDLER';
export const SET_INPUT_RANGE_VALUE = 'SET_INPUT_RANGE_VALUE';

export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';